#!/usr/bin/env bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "This script must be used only via 'make biblio-nourl.bib'"
    exit 0
fi

input_bib="$1"
temp_bib=$(mktemp -t bib-tmp.XXXXXXXXXX.bib)

# select entries whose URLs are to be kept
bibtool -r <(cat .bibtoolrsc .bibtoolrsc-url) -i "$input_bib" > "$temp_bib"

# append entries whose URLs are to be deleted
bibtool -r <(cat .bibtoolrsc .bibtoolrsc-nomisc) -i "$input_bib" \
    | bibtool -r <(cat .bibtoolrsc .bibtoolrsc-noarxiv) \
    | bibtool -r <(cat .bibtoolrsc .bibtoolrsc-nourl) >> "$temp_bib"

# format result according to the rules defined in '.bibtoolrsc'
echo "%%%%% AUTOGENERATED -- DO NOT EDIT %%%%%"
echo
bibtool -r .bibtoolrsc -i "$temp_bib"
